/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ComponentsImport } from './routes/components'
import { Route as IndexImport } from './routes/index'
import { Route as GeneralResourcesImport } from './routes/general/resources'
import { Route as ComponentsTableIndexImport } from './routes/components/table/index'
import { Route as ComponentsButtonIndexImport } from './routes/components/button/index'
import { Route as ComponentsTableLoadOnScrollSpinnerImport } from './routes/components/table/loadOnScrollSpinner'
import { Route as ComponentsTableLoadOnScrollImport } from './routes/components/table/loadOnScroll'
import { Route as ComponentsButtonExample2Import } from './routes/components/button/example2'

// Create/Update Routes

const ComponentsRoute = ComponentsImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GeneralResourcesRoute = GeneralResourcesImport.update({
  id: '/general/resources',
  path: '/general/resources',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsTableIndexRoute = ComponentsTableIndexImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => ComponentsRoute,
} as any)

const ComponentsButtonIndexRoute = ComponentsButtonIndexImport.update({
  id: '/button/',
  path: '/button/',
  getParentRoute: () => ComponentsRoute,
} as any)

const ComponentsTableLoadOnScrollSpinnerRoute =
  ComponentsTableLoadOnScrollSpinnerImport.update({
    id: '/table/loadOnScrollSpinner',
    path: '/table/loadOnScrollSpinner',
    getParentRoute: () => ComponentsRoute,
  } as any)

const ComponentsTableLoadOnScrollRoute =
  ComponentsTableLoadOnScrollImport.update({
    id: '/table/loadOnScroll',
    path: '/table/loadOnScroll',
    getParentRoute: () => ComponentsRoute,
  } as any)

const ComponentsButtonExample2Route = ComponentsButtonExample2Import.update({
  id: '/button/example2',
  path: '/button/example2',
  getParentRoute: () => ComponentsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsImport
      parentRoute: typeof rootRoute
    }
    '/general/resources': {
      id: '/general/resources'
      path: '/general/resources'
      fullPath: '/general/resources'
      preLoaderRoute: typeof GeneralResourcesImport
      parentRoute: typeof rootRoute
    }
    '/components/button/example2': {
      id: '/components/button/example2'
      path: '/button/example2'
      fullPath: '/components/button/example2'
      preLoaderRoute: typeof ComponentsButtonExample2Import
      parentRoute: typeof ComponentsImport
    }
    '/components/table/loadOnScroll': {
      id: '/components/table/loadOnScroll'
      path: '/table/loadOnScroll'
      fullPath: '/components/table/loadOnScroll'
      preLoaderRoute: typeof ComponentsTableLoadOnScrollImport
      parentRoute: typeof ComponentsImport
    }
    '/components/table/loadOnScrollSpinner': {
      id: '/components/table/loadOnScrollSpinner'
      path: '/table/loadOnScrollSpinner'
      fullPath: '/components/table/loadOnScrollSpinner'
      preLoaderRoute: typeof ComponentsTableLoadOnScrollSpinnerImport
      parentRoute: typeof ComponentsImport
    }
    '/components/button/': {
      id: '/components/button/'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonIndexImport
      parentRoute: typeof ComponentsImport
    }
    '/components/table/': {
      id: '/components/table/'
      path: '/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableIndexImport
      parentRoute: typeof ComponentsImport
    }
  }
}

// Create and export the route tree

interface ComponentsRouteChildren {
  ComponentsButtonExample2Route: typeof ComponentsButtonExample2Route
  ComponentsTableLoadOnScrollRoute: typeof ComponentsTableLoadOnScrollRoute
  ComponentsTableLoadOnScrollSpinnerRoute: typeof ComponentsTableLoadOnScrollSpinnerRoute
  ComponentsButtonIndexRoute: typeof ComponentsButtonIndexRoute
  ComponentsTableIndexRoute: typeof ComponentsTableIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsButtonExample2Route: ComponentsButtonExample2Route,
  ComponentsTableLoadOnScrollRoute: ComponentsTableLoadOnScrollRoute,
  ComponentsTableLoadOnScrollSpinnerRoute:
    ComponentsTableLoadOnScrollSpinnerRoute,
  ComponentsButtonIndexRoute: ComponentsButtonIndexRoute,
  ComponentsTableIndexRoute: ComponentsTableIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/general/resources': typeof GeneralResourcesRoute
  '/components/button/example2': typeof ComponentsButtonExample2Route
  '/components/table/loadOnScroll': typeof ComponentsTableLoadOnScrollRoute
  '/components/table/loadOnScrollSpinner': typeof ComponentsTableLoadOnScrollSpinnerRoute
  '/components/button': typeof ComponentsButtonIndexRoute
  '/components/table': typeof ComponentsTableIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/general/resources': typeof GeneralResourcesRoute
  '/components/button/example2': typeof ComponentsButtonExample2Route
  '/components/table/loadOnScroll': typeof ComponentsTableLoadOnScrollRoute
  '/components/table/loadOnScrollSpinner': typeof ComponentsTableLoadOnScrollSpinnerRoute
  '/components/button': typeof ComponentsButtonIndexRoute
  '/components/table': typeof ComponentsTableIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/general/resources': typeof GeneralResourcesRoute
  '/components/button/example2': typeof ComponentsButtonExample2Route
  '/components/table/loadOnScroll': typeof ComponentsTableLoadOnScrollRoute
  '/components/table/loadOnScrollSpinner': typeof ComponentsTableLoadOnScrollSpinnerRoute
  '/components/button/': typeof ComponentsButtonIndexRoute
  '/components/table/': typeof ComponentsTableIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/general/resources'
    | '/components/button/example2'
    | '/components/table/loadOnScroll'
    | '/components/table/loadOnScrollSpinner'
    | '/components/button'
    | '/components/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/general/resources'
    | '/components/button/example2'
    | '/components/table/loadOnScroll'
    | '/components/table/loadOnScrollSpinner'
    | '/components/button'
    | '/components/table'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/general/resources'
    | '/components/button/example2'
    | '/components/table/loadOnScroll'
    | '/components/table/loadOnScrollSpinner'
    | '/components/button/'
    | '/components/table/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  GeneralResourcesRoute: typeof GeneralResourcesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  GeneralResourcesRoute: GeneralResourcesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/components",
        "/general/resources"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/components": {
      "filePath": "components.tsx",
      "children": [
        "/components/button/example2",
        "/components/table/loadOnScroll",
        "/components/table/loadOnScrollSpinner",
        "/components/button/",
        "/components/table/"
      ]
    },
    "/general/resources": {
      "filePath": "general/resources.tsx"
    },
    "/components/button/example2": {
      "filePath": "components/button/example2.tsx",
      "parent": "/components"
    },
    "/components/table/loadOnScroll": {
      "filePath": "components/table/loadOnScroll.tsx",
      "parent": "/components"
    },
    "/components/table/loadOnScrollSpinner": {
      "filePath": "components/table/loadOnScrollSpinner.tsx",
      "parent": "/components"
    },
    "/components/button/": {
      "filePath": "components/button/index.tsx",
      "parent": "/components"
    },
    "/components/table/": {
      "filePath": "components/table/index.tsx",
      "parent": "/components"
    }
  }
}
ROUTE_MANIFEST_END */
